[[main]]
  name = "Journal"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Dev Log"
  pageRef = "devlog"
  weight = 20

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 30

[[main]]
  name = "Exam Portfolio"
  pageRef = "exam-portfolio"
  weight = 40
